name: Publish distributions to PyPI and TestPyPI
on: push

jobs:
  build-and-publish:
    name: Build and publish distributions to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        version: 3.7
    - name: Install wheel
      run: >-
        pip install wheel
    - name: Build
      run: >-
        python3 setup.py sdist bdist_wheel
    - name: Publish distribution to Test PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets._PYPI_TEST_ZIGPY_ }}
        repository_url: https://test.pypi.org/legacy/
